name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "lua/**"
      - "plugin/**"
      - "Makefile"
      - ".mise.toml"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      MISE_EXPERIMENTAL: true
      MINI_PATH: ${{ github.workspace }}/.ci/mini.nvim
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4

      - name: Install configured tools
        run: mise install

      - name: Run install task
        run: mise run install

      - name: Generate docs
        run: mise run docs

      - name: Commit docs
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: "chore(docs): regenerate vim help"