name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "lua/**"
      - "plugin/**"
      - "Makefile"
      - ".mise.toml"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      MISE_EXPERIMENTAL: true
      MINI_PATH: ${{ github.workspace }}/.ci/mini.nvim
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install mise
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3

      - name: Install configured tools
        run: mise install

      - name: Run install task
        run: mise run install

      - name: Generate docs
        run: mise run docs

      - name: Commit docs
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: "chore(docs): regenerate vim help"