name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@9558d9e0b4cf7ce0bd0786f7300f2aae0eab0683
    with:
      install: true
      lint: true
