name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@bcaf4ae43edf7d26421741424b82c842c83e55ce
    with:
      install: true
      test: true
      task-env: |
        MINI_PATH=${{ github.workspace }}/.ci/mini.nvim